[tools]
awscli = "2.17.18"
kubectl = "1.30.3"
terraform = "1.9.6"
kotlin = "2.0.20"
elixir = "1.19.4-otp-28"
erlang = "28.2"
node = "22.17.0"
yarn = "4.6.0"
deno = "2.1.9"
go = "1.25.4" 
rust = "nightly"
pnpm = "10.15.0"
gleam = "1.12.0"
lua = "5.4.8"
sops = "3.11.0"
age = "1.2.1"
