[tools]
awscli = "2.33.19"
kubectl = "1.35.1"
terraform = "1.14.5"
kotlin = "2.3.10"
elixir = "1.19.4-otp-28"
erlang = "28.3.1"
node = "25.6.1"
yarn = "4.9.4"
deno = "2.1.9"
go = "1.26.0"
rust = "nightly"
pnpm = "10.29.3"
gleam = "1.14.0"
lua = "5.4.8"
sops = "3.11.0"
age = "1.3.1"
